CREATE TABLE IF NOT EXISTS `dogs_learned_skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dog_id` INT NOT NULL,
  `skill_key` VARCHAR(12) NOT NULL,
  `last_trained` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`dog_id`) REFERENCES dogs(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`skill_key`) REFERENCES dogs_skills(`key`) ON UPDATE CASCADE ON DELETE CASCADE
);